CREATE DATA BASE IF NOT EXIST development;

CREATE TABLE IF NOT EXISTS Category (
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  id SERIAL PRIMARY KEY,
);
CREATE TABLE IF NOT EXISTS Imagen (
  ruta INTEGER NOT NULL,
  id SERIAL PRIMARY KEY,
);

CREATE TABLE IF NOT EXISTS Order_Product (
  quantity INTEGER NOT NULL,
  price FLOAT NOT NULL,
  id SERIAL PRIMARY KEY,
);
CREATE TABLE IF NOT EXISTS Order (
  state VARCHAR(255) NOT NULL,
  id SERIAL PRIMARY KEY,
);
CREATE TABLE IF NOT EXISTS Product (
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  stock INTEGER NOT NULL,
  image VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  id SERIAL PRIMARY KEY,
);
CREATE TABLE IF NOT EXISTS Review (
  comments VARCHAR(255) NOT NULL,
  score INTEGER NOT NULL,
  id SERIAL PRIMARY KEY,
);
CREATE TABLE IF NOT EXISTS User (
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255)  NOT NULL,
  isAdmin BOOLEAN NOT NULL,
  isGoogle BOOLEAN NOT NULL,
  imageGoogle VARCHAR(255) NOT NULL,
  resetPassword BOOLEAN NOT NULL,
  active BOOLEAN NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  postalcode VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  id SERIAL PRIMARY KEY,
);


